### ISSUE TITLE
minecraft won't start

### ISSUE THREAD

**Issue by nsevenart** [MinecraftMachina/multimc-macos-arm64#24]
minecraft won't start and says error 255
[06:23:07] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[06:23:07] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[06:23:07] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[06:23:07] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[06:23:07] [Render thread/INFO]: [STDERR]: 	at ac.a(SourceFile:65)
[06:23:07] [Render thread/INFO]: [STDERR]: 	at dxo.a(SourceFile:2420)
[06:23:07] [Render thread/INFO]: [STDERR]: 	at dxo.a(SourceFile:2415)
[06:23:07] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:208)
[06:23:07] [Render thread/INFO]: [STDERR]: 	... 8 more
[06:23:07] [Render thread/INFO]: [STDOUT]: Exiting with -1

**Comment by ViRb3** [comment]
Check the [troubleshooting](https://github.com/MinecraftMachina/ManyMC#troubleshooting) section. If this is Minecraft 1.16 or before, make sure you use Java 8, not higher.
