### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by theemutvcode** [MinecraftMachina/multimc-macos-arm64#47]
!! Please fill in this template, DO NOT ignore or delete it. !!

**I tried basic troubleshooting first**

- [x] Carefully read the [installation guide](https://github.com/MinecraftMachina/ManyMC#install)
- [x] Carefully read the [troubleshooting guide](https://github.com/MinecraftMachina/ManyMC#troubleshooting)

**Describe the bug**

Minecraft crashes on start when using forge.

**To reproduce**

Install Forge 35.1.37 in ManyMC with Minecraft 1.16.4 and Java 8.

**Expected behavior**

I expected Minecraft to start normally with Forge.

**Logs**

ManyMC version: 0.0.7-custom

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.66.119.42, 18.66.119.38, 18.66.119.37, 18.66.119.35]

session.minecraft.net resolves to:
    [3.211.39.224, 3.224.239.34, 52.205.99.166]

textures.minecraft.net resolves to:
    [99.86.7.107, 99.86.7.90, 99.86.7.25, 99.86.7.19]

api.mojang.com resolves to:
    [143.204.215.118, 143.204.215.18, 143.204.215.65, 143.204.215.116]

Minecraft folder is:
/Users/emily/Library/Application Support/ManyMC/instances/1.16.4/.minecraft

Java path is:
/Users/emily/zulu-8.jdk/Contents/Home/bin/java

Checking Java version...
Java is version 1.8.0_322, using aarch64 architecture, from Azul Systems, Inc..

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  /Users/emily/Library/Application Support/ManyMC/instances/1.16.4/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /Users/emily/Library/Application Support/ManyMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/ca/weblite/java-objc-bridge/1.1.0-mmachina.1/java-objc-bridge-1.1.0-mmachina.1.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1-mmachina.1/lwjgl-glfw-3.3.1-mmachina.1.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1-mmachina.1/lwjgl-jemalloc-3.3.1-mmachina.1.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl-openal/3.3.1-mmachina.1/lwjgl-openal-3.3.1-mmachina.1.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1-mmachina.1/lwjgl-opengl-3.3.1-mmachina.1.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl-stb/3.3.1-mmachina.1/lwjgl-stb-3.3.1-mmachina.1.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1-mmachina.1/lwjgl-tinyfd-3.3.1-mmachina.1.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl/3.3.1-mmachina.1/lwjgl-3.3.1-mmachina.1.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/net/minecraftforge/forge/1.16.4-35.1.37/forge-1.16.4-35.1.37-launcher.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/ow2/asm/asm/9.0/asm-9.0.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/ow2/asm/asm-commons/9.0/asm-commons-9.0.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/ow2/asm/asm-tree/9.0/asm-tree-9.0.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/ow2/asm/asm-util/9.0/asm-util-9.0.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/ow2/asm/asm-analysis/9.0/asm-analysis-9.0.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/cpw/mods/grossjava9hacks/1.3.0/grossjava9hacks-1.3.0.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/net/minecraftforge/coremods/4.0.3/coremods-4.0.3.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/com/electronwill/night-config/core/3.6.2/core-3.6.2.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/com/electronwill/night-config/toml/3.6.2/toml-3.6.2.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/apache/maven/maven-artifact/3.6.0/maven-artifact-3.6.0.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1/nashorn-core-compat-15.1.1.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/com/mojang/minecraft/1.16.4/minecraft-1.16.4-client.jar

Native libraries:
  /Users/emily/Library/Application Support/ManyMC/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1-mmachina.1/lwjgl-glfw-3.3.1-mmachina.1-natives-macos.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1-mmachina.1/lwjgl-jemalloc-3.3.1-mmachina.1-natives-macos.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl-openal/3.3.1-mmachina.1/lwjgl-openal-3.3.1-mmachina.1-natives-macos.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1-mmachina.1/lwjgl-opengl-3.3.1-mmachina.1-natives-macos.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl-stb/3.3.1-mmachina.1/lwjgl-stb-3.3.1-mmachina.1-natives-macos.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1-mmachina.1/lwjgl-tinyfd-3.3.1-mmachina.1-natives-macos.jar
  /Users/emily/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl/3.3.1-mmachina.1/lwjgl-3.3.1-mmachina.1-natives-macos.jar

Mods:
  [✔️] [1.16.5] SecurityCraft v1.8.21.1
  [✔️] appliedenergistics2-8.2.0
  [✔️] car-1.16.4-1.0.5
  [✔️] cfm-7.0.0pre22-1.16.3
  [✔️] chiseled0.3.5
  [✔️] chiselsandbits-1.0.63
  [✔️] CodeChickenLib-1.16.4-3.5.1.408-universal
  [✔️] jei-1.16.4-7.6.1.74
  [✔️] MouseTweaks-2.14-mc1.16.2
  [✔️] movingelevators-1.3.4-mc1.16
  [✔️] OPF-1.16.X-v1
  [✔️] OptiFine_1.16.4_HD_U_G7
  [✔️] simpleplanes-1.16.4-4.1.2
  [✔️] smallships-1.16.5-1.10.1
  [✔️] supermartijn642configlib-1.0.9-mc1.16
  [✔️] supermartijn642corelib-1.0.16-mc1.16.5
  [✔️] worldedit-mod-7.2.5-dist

Params:
  --username  --version MultiMC5 --gameDir /Users/emily/Library/Application Support/ManyMC/instances/1.16.4/.minecraft --assetsDir /Users/emily/Library/Application Support/ManyMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 35.1.37 --fml.mcVersion 1.16.4 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20201102.104115

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="ManyMC: 1.16.4", -XstartOnFirstThread, -Xms4096m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 1686

Using onesix launcher.

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2022-03-26 11:30:25,031 main WARN Advanced terminal features are not available in this environment
[11:30:25] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, theemuly, --version, MultiMC5, --gameDir, /Users/emily/Library/Application Support/ManyMC/instances/1.16.4/.minecraft, --assetsDir, /Users/emily/Library/Application Support/ManyMC/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ❄❄❄❄❄❄❄❄, --userType, msa, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 35.1.37, --fml.mcVersion, 1.16.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20201102.104115, --width, 854, --height, 480]
[11:30:25] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_322 by Azul Systems, Inc.
[11:30:25] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[11:30:25] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: /Users/emily/Library/Application Support/ManyMC/instances/1.16.4/.minecraft/mods/OptiFine_1.16.4_HD_U_G7.jar
[11:30:25] [main/INFO] [op.OptiFineTransformer/]: Target.PRE_CLASS is available
[11:30:25] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[11:30:25] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/Users/emily/Library/Application%20Support/ManyMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[11:30:25] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[11:30:25] [main/WARN] [ne.mi.fm.lo.FMLConfig/CORE]: Configuration file /Users/emily/Library/Application Support/ManyMC/instances/1.16.4/.minecraft/config/fml.toml is not correct. Correcting
[11:30:25] [main/WARN] [ne.mi.fm.lo.FMLConfig/CORE]: Incorrect key [defaultConfigPath] was corrected from null to defaultconfigs
[11:30:26] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[11:30:26] [main/INFO] [op.OptiFineTransformer/]: Targets: 308
[11:30:26] [main/INFO] [op.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[11:30:26] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, MultiMC5, --gameDir, /Users/emily/Library/Application Support/ManyMC/instances/1.16.4/.minecraft, --assetsDir, /Users/emily/Library/Application Support/ManyMC/assets, --uuid, <PROFILE ID>, --username, theemuly, --assetIndex, 1.16, --accessToken, ❄❄❄❄❄❄❄❄, --userType, msa, --versionType, release, --width, 854, --height, 480]
[11:30:27] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[11:30:27] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: java.lang.reflect.InvocationTargetException
[11:30:27] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:30:27] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:30:27] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:30:27] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:30:27] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[11:30:27] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[11:30:27] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[11:30:27] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[11:30:27] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: Caused by: java.lang.reflect.InvocationTargetException
[11:30:27] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:30:27] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:30:27] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:30:27] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:30:27] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[11:30:27] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	... 8 more
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	... 13 more
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: Caused by: java.lang.reflect.InvocationTargetException
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	... 17 more
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at net.minecraft.util.math.MathHelper.<clinit>(MathHelper.java:20)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at net.minecraft.util.Util.func_240979_a_(Util.java:109)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at net.minecraft.util.Util.<clinit>(Util.java:65)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at net.minecraft.client.main.Main.main(Main.java:63)
[11:30:27] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	... 23 more
[11:30:27] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Process exited with code 255.
Clipboard copy at: 26 Mar 2022 11:33:26 +0100

**Screenshots**

<img width="467" alt="image" src="https://user-images.githubusercontent.com/55019667/160235628-e8c397f9-837b-4781-a0df-b7accdf5d6c0.png">
<img width="541" alt="image" src="https://user-images.githubusercontent.com/55019667/160235639-789df59b-374b-44f3-8ca5-405b305e0776.png">

**System configuration**

- ManyMC version: 0.0.7
- Java version: Azul JDK 8

**Comment by theemutvcode** [comment]
I was able to fix it. I just needed to change my java installation to this one:
https://cdn.azul.com/zulu/bin/zulu8.56.0.23-ca-jdk8.0.302-macosx_aarch64.zip
