### ISSUE TITLE
Error 255 on no modded Minecraft 1.19 version 

### ISSUE THREAD

**Issue by yukifolf** [MinecraftMachina/multimc-macos-arm64#79]
Hi,
My Minecraft instance throw an error 255 while I want to start it. Below is my crash report.
I don't know what's wrong with my Minecraft config or java version (zulu-17).

```
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 8/7/22, 8:25 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
        at eez.<init>(SourceFile:799)
        at eev.<init>(SourceFile:445)
        at net.minecraft.client.main.Main.main(SourceFile:198)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
        at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
        at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
        at org.multimc.EntryPoint.listen(EntryPoint.java:127)
        at org.multimc.EntryPoint.main(EntryPoint.java:57)
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Failed to locate library: libglfw.dylib
        at dyn.<clinit>(SourceFile:44)
        ... 12 more
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: libglfw.dylib
        at org.lwjgl.system.Library.loadNative(Library.java:327)
        at org.lwjgl.system.Library.loadNative(Library.java:224)
        at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:30)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
        at java.base/java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:377)
        at java.base/java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:374)
        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
        at java.base/java.lang.ClassValue.get(ClassValue.java:116)
        at java.base/java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:400)
        at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:388)
        at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:422)
        at dyn.<clinit>(SourceFile:41)
        ... 12 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
        at eez.<init>(SourceFile:799)
        at eev.<init>(SourceFile:445)

-- Initialization --
Details:
        Modules: 
Stacktrace:
        at net.minecraft.client.main.Main.main(SourceFile:198)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
        at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
        at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
        at org.multimc.EntryPoint.listen(EntryPoint.java:127)
        at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- System Details --
Details:
        Minecraft Version: 1.19
        Minecraft Version ID: 1.19
        Operating System: Mac OS X (aarch64) version 12.5
        Java Version: 17.0.4, Azul Systems, Inc.
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
        Memory: 913140288 bytes (870 MiB) / 2030043136 bytes (1936 MiB) up to 8598323200 bytes (8200 MiB)
        CPUs: 8
        Processor Vendor: Apple Inc.
        Processor Name: Apple M1
        Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
        Microarchitecture: ARM64 SoC: Firestorm + Icestorm
        Frequency (GHz): 24.00
        Number of physical packages: 1
        Number of physical CPUs: 8
        Number of logical CPUs: 8
        Graphics card #0 name: Apple M1
        Graphics card #0 vendor: Apple (0x106b)
        Graphics card #0 VRAM (MB): 0.00
        Graphics card #0 deviceId: unknown
        Graphics card #0 versionInfo: unknown
        Memory slot #0 capacity (MB): 0.00
        Memory slot #0 clockSpeed (GHz): 0.00
        Memory slot #0 type: unknown
        Virtual memory max (MB): 18432.00
        Virtual memory used (MB): 13120.20
        Swap memory total (MB): 2048.00
        Swap memory used (MB): 1156.94
        JVM Flags: 2 total; -Xms196m -Xmx8196m
        Launched Version: 1.19
        Backend library: LWJGL version 3.3.1 build 7
        Backend API: Unknown
        Window size: <not initialized>
        GL Caps: Using framebuffer using OpenGL 3.2
        GL debug messages: <disabled>
        Using VBOs: Yes
        Is Modded: Probably not. Client jar signature and brand is untouched
        Type: Client (map_client.txt)
        CPU: <unknown>%  
```

**Comment by ViRb3** [comment]
There is something wrong with your ManyMC settings. Make sure you are not using any m1 hacks/wrappers. You may also have a problematic mod, so try without mods. If nothing helps, reset your ManyMC settings by removing: `~/Library/Application Support/ManyMC`. NOTE: ALL INSTANCES WILL BE LOST!
